package com.project.XXcloud.Mbg.model;

import java.io.Serializable;
import java.util.Date;

public class LoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.log_id
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    private Integer logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.user_id
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.login_time
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.ip_address
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    private String ipAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.login_os
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    private String loginOs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.login_browser
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    private String loginBrowser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_log.create_date
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table login_log
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.log_id
     *
     * @return the value of login_log.log_id
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.log_id
     *
     * @param logId the value for login_log.log_id
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.user_id
     *
     * @return the value of login_log.user_id
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.user_id
     *
     * @param userId the value for login_log.user_id
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.login_time
     *
     * @return the value of login_log.login_time
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.login_time
     *
     * @param loginTime the value for login_log.login_time
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.ip_address
     *
     * @return the value of login_log.ip_address
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.ip_address
     *
     * @param ipAddress the value for login_log.ip_address
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.login_os
     *
     * @return the value of login_log.login_os
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public String getLoginOs() {
        return loginOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.login_os
     *
     * @param loginOs the value for login_log.login_os
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public void setLoginOs(String loginOs) {
        this.loginOs = loginOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.login_browser
     *
     * @return the value of login_log.login_browser
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public String getLoginBrowser() {
        return loginBrowser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.login_browser
     *
     * @param loginBrowser the value for login_log.login_browser
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public void setLoginBrowser(String loginBrowser) {
        this.loginBrowser = loginBrowser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_log.create_date
     *
     * @return the value of login_log.create_date
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_log.create_date
     *
     * @param createDate the value for login_log.create_date
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_log
     *
     * @mbggenerated Wed Jan 13 09:07:29 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", userId=").append(userId);
        sb.append(", loginTime=").append(loginTime);
        sb.append(", ipAddress=").append(ipAddress);
        sb.append(", loginOs=").append(loginOs);
        sb.append(", loginBrowser=").append(loginBrowser);
        sb.append(", createDate=").append(createDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}