package com.project.XXcloud.Mbg.Model;

import java.io.Serializable;
import java.util.Date;

public class UserFile implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.file_id
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    private Integer fileId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_id
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.file_name
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.create_date
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.file_type
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    private Integer fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_file
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_id
     *
     * @return the value of user_file.file_id
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_id
     *
     * @param fileId the value for user_file.file_id
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_id
     *
     * @return the value of user_file.user_id
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_id
     *
     * @param userId the value for user_file.user_id
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_name
     *
     * @return the value of user_file.file_name
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_name
     *
     * @param fileName the value for user_file.file_name
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.create_date
     *
     * @return the value of user_file.create_date
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.create_date
     *
     * @param createDate the value for user_file.create_date
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_type
     *
     * @return the value of user_file.file_type
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_type
     *
     * @param fileType the value for user_file.file_type
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbggenerated Mon Mar 01 08:59:00 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", fileId=").append(fileId);
        sb.append(", userId=").append(userId);
        sb.append(", fileName=").append(fileName);
        sb.append(", createDate=").append(createDate);
        sb.append(", fileType=").append(fileType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}